
apiVersion: v1
kind: Namespace
metadata:
  name: config-connector
  annotations:
    cnrm.cloud.google.com/project-id: kubeshot-devops
---
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  # the name is restricted to ensure that there is only one
  # ConfigConnector resource installed in your cluster
  name: configconnector.core.cnrm.cloud.google.com
spec:
 mode: namespaced
