apiVersion: v1
kind: Namespace
metadata:
  name: project-a
  annotations:
    cnrm.cloud.google.com/organization-id: "No organization"
---
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  # you can only have one ConfigConnectorContext per namespace
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: project-a
spec:
  googleServiceAccount: "project-a@kubeshot-devops.iam.gserviceaccount.com"
---
  apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
  kind: PubSubTopic
  metadata:
    annotations:
      cnrm.cloud.google.com/project-id: kubeshot-devops
    labels:
      environment: test
    name: test-topic
    namespace: project-a
---
  apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
  kind: Project
  metadata:
    annotations:
      cnrm.cloud.google.com/auto-create-network: "false"
    labels:
      label-one: "value-one"
    name: project-sample-in-org
    namespace: project-a
  spec:
    name: Config Connector Sample
