apiVersion: v1
kind: Namespace
metadata:
  name: hub-project
  annotations:
    cnrm.cloud.google.com/organization-id: "252632484771"
---
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  # you can only have one ConfigConnectorContext per namespace
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: hub-project
spec:
  googleServiceAccount: "hub-project@kubeshot-devops.iam.gserviceaccount.com"
---
  apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
  kind: PubSubTopic
  metadata:
    annotations:
      cnrm.cloud.google.com/project-id: kubeshot-devops
    labels:
      environment: test
    name: test-topic
    namespace: hub-project
---
  apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
  kind: Project
  metadata:
    annotations:
      cnrm.cloud.google.com/auto-create-network: "false"
    labels:
      env: "test"
    name: kubeshot-test-project
    namespace: hub-project
  spec:
    name: Config Connector Sample
